"""add user model and relationships

Revision ID: 188d6be28d1a
Revises: fb6e2d1b2d60
Create Date: 2025-04-30 10:51:56.258632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188d6be28d1a'
down_revision: Union[str, None] = 'fb6e2d1b2d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_descriptions', 'users', ['user_id'], ['id'])
    op.add_column('resumes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'user_id')
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'user_id')
    # ### end Alembic commands ###
